name: react
on:
  push:
    branches:
      - 'main'
      
env:
  IMG_NAME: "react"
  TAG: "latest"      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3.0.0
        with:
          node-version: 16
          cache: 'npm'
          
      - name: Semantic versioning
        id: versioning
        uses: PaulHatch/semantic-version@v4.0.2
        with:
          branch: main
          tag_prefix: "v"
          major_pattern: "BREAKING CHANGE:"
          minor_pattern: "feat:"
          format: "v${major}.${minor}.${patch}-prereleases${increment}"
     
      - name: npm install
        run: | 
          npm install --save-dev semantic-release --force
          npm run build
      - name: version
        run: |
          echo ${{ steps.versioning.outputs.version }}  >> version.txt
          ls
          cat version.txt
      
       
      - name: Create Release
        uses: actions/create-release@v1
        env:
           GITHUB_TOKEN: ${{ github.token }}
        with:
          tag_name: ${{ steps.versioning.outputs.version }}
          release_name: ${{ steps.versioning.outputs.version }}
      
      
      
      
          
