name: react
on:
  push:
    branches:
      - 'main'
      
env:
  IMG_NAME: "react"
  TAG: "latest"      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3.0.0
        with:
          node-version: 16
          cache: 'npm'
          
      - name: npm install
        run: | 
          npm install --force
          npm run build
          npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
          
      
      
          
