name: react
on:
  push:
    branches:
      - 'main'
      
env:
  IMG_NAME: "react"
  TAG: "latest"      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3.0.0
        with:
          node-version: 16
          cache: 'npm'

      - name: Build
        run: |
          npm install --force
          npm run build
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v3
        with: 
          branches: |
            [
              '+([0-9])?(.{+([0-9]),x}).x',
              'main',
            ]
      
      # you can set branch for semantic-release older than v16.
          
        env:
          GITHUB_TOKEN: "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"
          
      - uses: actions/checkout@v2
      - uses: haya14busa/action-update-semver@v1
        id: version
        with:
          major_version_tag_only: true
          
      
      - name: Build image
        run: |
          tag_v=$(git describe --tags $(git rev-list --tags --max-count=1))
          tag=$(echo $tag_v | sed 's/v//')
          docker build -t react_${tag} .
      - name: ls
        run: docker images
