name: react
on:
  push:
    branches:
      - 'main'
      
env:
  IMG_NAME: "react"
  TAG: "latest"      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3.0.0
        with:
          node-version: 16
          cache: 'npm'
          
      - name: npm install
        run: | 
          npm install --force
          npx semantic-release
          npm run build
        env:
          GITHUB_TOKEN: "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"
      
          

      - name: Debug
        run: |
          echo "github.ref -> {{ github.ref }}"
      - name: Docker metadata
        id: metadata
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.IMG_NAME }}
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=raw,value={{sha}},enable=${{ github.ref_type != 'tag' }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: ${{ github.event.base_ref =='refs/heads/main' && github.ref_type == 'tag' && !startsWith(github.ref, 'refs/tags/v0.')}}
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}

      - name: ls
        run: docker images
