name: react
on:
  push:
    branches:
      - 'main'
      
env:
  IMG_NAME: "react"
  TAG: "latest"      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3.0.0
        with:
          node-version: 16
          cache: 'npm'

      - name: Build
        run: |
          npm install --force
          npm run build
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v3
        with:
          semantic_version: 15.13.28
      # you can set branch for semantic-release older than v16.
          branch: 'main'
          
      - name: docker
        run: docker build . --file Dockerfile --tag ${{ env.IMG_NAME }}:${{env.TAG}}
        
      - name: Tag
        run: |
          short_id=$(echo ${{github.run_id}} | cut -c 1-6)
          commit_id=$(echo ${{github.commit_id}} | cut -c 1-8)
          VERSION=$(cat VERSION)
          DOCKER_TAG_FULL=(${VERSION}_${commit_id}_${short_id}_${{ github.run_number }})
          docker tag ${{ env.IMG_NAME }}:${{env.TAG}} ${{ env.IMG_NAME }}:${DOCKER_TAG_FULL}
      - name: ls
        run: docker images
